name: CI

on: [push, pull_request]

jobs:
  build:
    name: Lint and test code base
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: isort
      run: |
        python -m isort $(git ls-files '*.py')

    - name: black
      run: |
        python -m black $(git ls-files '*.py') --check

    - name: flake8
      uses: py-actions/flake8@v2
      with:
        max-line-length: "79"
        exclude: "__init__.py"
        ignore: "W503"

    - name: autoflake
      uses: py-actions/flake8@v2
      with:
        max-line-length: "79"
        exclude: "__init__.py"
        ignore: "W503"

    - name: Test with pytest
      run: |
        python -m pytest
        --cov-fail-under 80
        src/tests

